##################################################
#                                                #
#   Makefile for CT Image Application Program    #
#                                                #
##################################################
# Some common definitions...

RM = rm -f
CXX = cc

# Compiler flags, paths for include files and libraries

CFLAGS = -O2
INCLUDES = -I. -I/usr/include -I/usr/include/X11
XMLIBS = -lXm -lXt -lXmu -lX11 -lmalloc

FILES = slice.o \
        label.o \
        menu.o \
        open.o \
        save.o \
        exit.o \
        measure.o \
        region.o \
        edge.o \
        ctomass.o \
	watershed.o \
	editing_tools.o \
	region_ops.o \
	zoom.o \
	split_merge.o \
	neighbour.o \
        print.o \
	version.o

# Rule to create .o files from .c files
.c.o:
	$(RM) $@
	$(CXX) -c $(CFLAGS) $(INCLUDES) $*.c
	
# Targets...

all::	slice

slice: $(FILES)
	$(RM) $@
	$(CXX) -o $@ $(CFLAGS) $(INCLUDES) $(FILES) $(XMLIBS) -lm
	

